version: '2'

services:

  orderer.reliance-network.com:
    container_name: orderer.reliance-network.com
    image: hyperledger/fabric-orderer:latest #x86_64-1.0.0-rc1
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      #- GODEBUG=netdns=go
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/reliance-network.com/orderers/orderer.reliance-network.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/reliance-network.com/orderers/orderer.reliance-network.com/tls/:/var/hyperledger/orderer/tls
    - orderer.reliance-network.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.Infrastructure.reliance-network.com:
    container_name: peer0.Infrastdructure.reliance-network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.Infrastructure.reliance-network.com
      - CORE_PEER_ADDRESS=peer0.Infrastructure.reliance-network.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.Infrastructure.reliance-network.com:7053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7053
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.Infrastructure.reliance-network.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.Infrastructure.reliance-network.com:7051
      - CORE_PEER_LOCALMSPID=InfrastructureMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/Infrastructure.reliance-network.com/peers/peer0.Infrastructure.reliance-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/Infrastructure.reliance-network.com/peers/peer0.Infrastructure.reliance-network.com/tls:/etc/hyperledger/fabric/tls
        - peer0.Infrastructure.reliance-network.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer1.Infrastructure.reliance-network.com:
    container_name: peer1.Infrastructure.reliance-network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.Infrastructure.reliance-network.com
      - CORE_PEER_ADDRESS=peer1.Infrastructure.reliance-network.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.Infrastructure.reliance-network.com:8053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.Infrastructure.reliance-network.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.Infrastructure.reliance-network.com:7051
      - CORE_PEER_LOCALMSPID=InfrastructureMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/Infrastructure.reliance-network.com/peers/peer1.Infrastructure.reliance-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/Infrastructure.reliance-network.com/peers/peer1.Infrastructure.reliance-network.com/tls:/etc/hyperledger/fabric/tls
        - peer1.Infrastructure.reliance-network.com:/var/hyperledger/production

    ports:
      - 8051:8051
      - 8053:8053

  peer0.Power.reliance-network.com:
    container_name: peer0.Power.reliance-network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.Power.reliance-network.com
      - CORE_PEER_ADDRESS=peer0.Power.reliance-network.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.Power.reliance-network.com:9053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.Power.reliance-network.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.Power.reliance-network.com:10051
      - CORE_PEER_LOCALMSPID=PowerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/Power.reliance-network.com/peers/peer0.Power.reliance-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/Power.reliance-network.com/peers/peer0.Power.reliance-network.com/tls:/etc/hyperledger/fabric/tls
        - peer0.Power.reliance-network.com:/var/hyperledger/production
    ports:
      - 9051:9051
      - 9053:9053

  peer1.Power.reliance-network.com:
    container_name: peer1.Power.reliance-network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.Power.reliance-network.com
      - CORE_PEER_ADDRESS=peer1.Power.reliance-network.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.Power.reliance-network.com:10053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.Power.reliance-network.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.Power.reliance-network.com:9051
      - CORE_PEER_LOCALMSPID=PowerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/Power.reliance-network.com/peers/peer1.Power.reliance-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/Power.reliance-network.com/peers/peer1.Power.reliance-network.com/tls:/etc/hyperledger/fabric/tls
        - peer1.Power.reliance-network.com:/var/hyperledger/production
    ports:
      - 10051:10051
      - 10053:10053

  peer0.Communications.reliance-network.com:
    container_name: peer0.Communications.reliance-network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.Communications.reliance-network.com
      - CORE_PEER_ADDRESS=peer0.Communications.reliance-network.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.Communications.reliance-network.com:11053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.Communications.reliance-network.com:11051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.Communications.reliance-network.com:12051
      - CORE_PEER_LOCALMSPID=CommunicationsMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/Communications.reliance-network.com/peers/peer0.Communications.reliance-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/Communications.reliance-network.com/peers/peer0.Communications.reliance-network.com/tls:/etc/hyperledger/fabric/tls
        - peer0.Communications.reliance-network.com:/var/hyperledger/production
    ports:
      - 11051:11051
      - 11053:11053

  peer1.Communications.reliance-network.com:
    container_name: peer1.Communications.reliance-network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.Communications.reliance-network.com
      - CORE_PEER_ADDRESS=peer1.Communications.reliance-network.com:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_CHAINCODEADDRESS=peer1.Communications.reliance-network.com:12053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.Communications.reliance-network.com:12051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.Communications.reliance-network.com:11051
      - CORE_PEER_LOCALMSPID=CommunicationsMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/Communications.reliance-network.com/peers/peer1.Communications.reliance-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/Communications.reliance-network.com/peers/peer1.Communications.reliance-network.com/tls:/etc/hyperledger/fabric/tls
        - peer1.Communications.reliance-network.com:/var/hyperledger/production
    ports:
      - 12051:12051
      - 12053:12053

  peer0.Entertainment.reliance-network.com:
    container_name: peer0.Entertainment.reliance-network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.Entertainment.reliance-network.com
      - CORE_PEER_ADDRESS=peer0.Entertainment.reliance-network.com:13051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:13051
      - CORE_PEER_CHAINCODEADDRESS=peer0.Entertainment.reliance-network.com:13053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:13053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.Entertainment.reliance-network.com:13051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.Entertainment.reliance-network.com:14051
      - CORE_PEER_LOCALMSPID=EntertainmentMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/Entertainment.reliance-network.com/peers/peer0.Entertainment.reliance-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/Entertainment.reliance-network.com/peers/peer0.Entertainment.reliance-network.com/tls:/etc/hyperledger/fabric/tls
        - peer0.Entertainment.reliance-network.com:/var/hyperledger/production
    ports:
      - 13051:13051
      - 13053:13053

  peer1.Entertainment.reliance-network.com:
    container_name: peer1.Entertainment.reliance-network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.Entertainment.reliance-network.com
      - CORE_PEER_ADDRESS=peer1.Entertainment.reliance-network.com:14051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:14051
      - CORE_PEER_CHAINCODEADDRESS=peer1.Entertainment.reliance-network.com:14053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:14053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.Entertainment.reliance-network.com:14051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.Entertainment.reliance-network.com:13051
      - CORE_PEER_LOCALMSPID=EntertainmentMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/Entertainment.reliance-network.com/peers/peer1.Entertainment.reliance-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/Entertainment.reliance-network.com/peers/peer1.Entertainment.reliance-network.com/tls:/etc/hyperledger/fabric/tls
        - peer1.Entertainment.reliance-network.com:/var/hyperledger/production
    ports:
      - 14051:14051
      - 14053:14053

  peer0.Capital.reliance-network.com:
    container_name: peer0.Capital.reliance-network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.Capital.reliance-network.com
      - CORE_PEER_ADDRESS=peer0.Capital.reliance-network.com:15051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:15051
      - CORE_PEER_CHAINCODEADDRESS=peer0.Capital.reliance-network.com:15053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:15053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.Capital.reliance-network.com:15051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.Capital.reliance-network.com:16051
      - CORE_PEER_LOCALMSPID=CapitalMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/Capital.reliance-network.com/peers/peer0.Capital.reliance-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/Capital.reliance-network.com/peers/peer0.Capital.reliance-network.com/tls:/etc/hyperledger/fabric/tls
        - peer0.Capital.reliance-network.com:/var/hyperledger/production
    ports:
      - 15051:15051
      - 15053:15053

  peer1.Capital.reliance-network.com:
    container_name: peer1.Capital.reliance-network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.Capital.reliance-network.com
      - CORE_PEER_ADDRESS=peer1.Capital.reliance-network.com:16051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:16051
      - CORE_PEER_CHAINCODEADDRESS=peer1.Capital.reliance-network.com:16053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:16053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.Capital.reliance-network.com:16051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.Capital.reliance-network.com:15051
      - CORE_PEER_LOCALMSPID=CapitalMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/Capital.reliance-network.com/peers/peer1.Capital.reliance-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/Capital.reliance-network.com/peers/peer1.Capital.reliance-network.com/tls:/etc/hyperledger/fabric/tls
        - peer1.Capital.reliance-network.com:/var/hyperledger/production
    ports:
      - 16051:16051
      - 16053:16053